spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle:  0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  application:
    name: admin-server
mybatis:
  type-aliases-package: com.alen.springboot.demo.entity
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com.alen.springboot.demo.dao: DEBUG
pagehelper:
  params: count=countSql
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true

server:
  port: 8080



#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        #显示健康细节
#  endpoint:
#    health:
#      show-details: ALWAYS

info:
  alen: alen
